api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    collection:
        pagination:
            items_per_page: 2 # Default value
            client_enabled: true
            enabled_parameter_name: pagination # optional

    exception_to_status:
        # The 4 following handlers are registered by default, keep those lines to prevent unexpected side effects
        Symfony\Component\Serializer\Exception\ExceptionInterface: 400 # Use a raw status code (recommended)
        ApiPlatform\Core\Exception\InvalidArgumentException: !php/const Symfony\Component\HttpFoundation\Response::HTTP_BAD_REQUEST
        ApiPlatform\Core\Exception\FilterValidationException: 400
        Doctrine\ORM\OptimisticLockException: 409

        # Custom mapping
        App\Exception\CustomException: 404 # Here is the handler for our custom exception
        # plus gdzies juz mam 401 gdy token nieprawidlowy

    http_cache:
        invalidation:
            enabled: true
            varnish_urls: []
        max_age: 3600
        shared_max_age: 3600
        vary: ['Content-Type', 'Authorization', 'Origin']
        public: true
